//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDat.LanguageServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDat.LanguageServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All assets that can exist in the bundle for this asset. These are the objects packaged in this asset&apos;s folder in the masterbundle..
        /// </summary>
        internal static string AssetList_BundleAssetsHeaderTooltip {
            get {
                return ResourceManager.GetString("AssetList_BundleAssetsHeaderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find installed location of Visual Studio Code..
        /// </summary>
        internal static string Error_FailedToFindVscode {
            get {
                return ResourceManager.GetString("Error_FailedToFindVscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear file association for &quot;{0}&quot; files..
        /// </summary>
        internal static string Error_FileAssocFailedToClear {
            get {
                return ResourceManager.GetString("Error_FileAssocFailedToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create VSCode file association for ProgId &quot;{0}&quot;..
        /// </summary>
        internal static string Error_FileAssocFailedToCreate {
            get {
                return ResourceManager.GetString("Error_FileAssocFailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run &quot;{0}&quot;. Exit code: &quot;{1}&quot;..
        /// </summary>
        internal static string Error_RegSvr32Exception {
            get {
                return ResourceManager.GetString("Error_RegSvr32Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find regsvr32.exe at &quot;{0}&quot;, which is needed to register file associations. Falling back to regsvr32 in PATH..
        /// </summary>
        internal static string Error_RegSvr32NotFound {
            get {
                return ResourceManager.GetString("Error_RegSvr32NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out running &quot;{0}&quot; to set up file associations..
        /// </summary>
        internal static string Error_RegSvr32Timeout {
            get {
                return ResourceManager.GetString("Error_RegSvr32Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added in.
        /// </summary>
        internal static string Hover_AddedVersion {
            get {
                return ResourceManager.GetString("Hover_AddedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string Hover_DictionaryTitle {
            get {
                return ResourceManager.GetString("Hover_DictionaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string Hover_InvalidValue {
            get {
                return ResourceManager.GetString("Hover_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string Hover_ListTitle {
            get {
                return ResourceManager.GetString("Hover_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Property.
        /// </summary>
        internal static string Hover_UnknownProperty {
            get {
                return ResourceManager.GetString("Hover_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unturned Documentation.
        /// </summary>
        internal static string Hover_UnturnedDocumentationLinkName {
            get {
                return ResourceManager.GetString("Hover_UnturnedDocumentationLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Hover_ValueTitle {
            get {
                return ResourceManager.GetString("Hover_ValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up cache files used by the Unturned Data File language server. This includes downloaded asset specifications and uncompressed bundles (which can get quite large)..
        /// </summary>
        internal static string WindowsDiskCleanup_Description {
            get {
                return ResourceManager.GetString("WindowsDiskCleanup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unturned Data File Language Server.
        /// </summary>
        internal static string WindowsDiskCleanup_Display {
            get {
                return ResourceManager.GetString("WindowsDiskCleanup_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register this extension&apos;s cache folder with the Windows Disk Cleanup utility, it needs to modify the machine&apos;s registry, which requires elevated permissions. The following command will be ran with elevated permissions, after which the extension will continue to run as a normal user: &apos;{0}&apos;. Would you like to proceed or skip this step?.
        /// </summary>
        internal static string WindowsDiskCleanup_PermissionRequest {
            get {
                return ResourceManager.GetString("WindowsDiskCleanup_PermissionRequest", resourceCulture);
            }
        }
    }
}
