//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDataFileLspServer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDataFileLspServer.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums can not have a base type..
        /// </summary>
        internal static string ArgumentException_BaseTypeNotAllowedForEnums {
            get {
                return ResourceManager.GetString("ArgumentException_BaseTypeNotAllowedForEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casing and value must have the same length..
        /// </summary>
        internal static string ArgumentException_CasingValueLengthMismatch {
            get {
                return ResourceManager.GetString("ArgumentException_CasingValueLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value list can not contain a value made up of other values..
        /// </summary>
        internal static string ArgumentException_CompositeFlagValue {
            get {
                return ResourceManager.GetString("ArgumentException_CompositeFlagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any animal..
        /// </summary>
        internal static string Description_EAssetType_ANIMAL {
            get {
                return ResourceManager.GetString("Description_EAssetType_ANIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any world effect or UI..
        /// </summary>
        internal static string Description_EAssetType_EFFECT {
            get {
                return ResourceManager.GetString("Description_EAssetType_EFFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any item..
        /// </summary>
        internal static string Description_EAssetType_ITEM {
            get {
                return ResourceManager.GetString("Description_EAssetType_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mythical cosmetic effect..
        /// </summary>
        internal static string Description_EAssetType_MYTHIC {
            get {
                return ResourceManager.GetString("Description_EAssetType_MYTHIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t fall into a legacy category. In this case short IDs are not used..
        /// </summary>
        internal static string Description_EAssetType_NONE {
            get {
                return ResourceManager.GetString("Description_EAssetType_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dialogue, quest, or vendor configuration..
        /// </summary>
        internal static string Description_EAssetType_NPC {
            get {
                return ResourceManager.GetString("Description_EAssetType_NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any level object or NPC..
        /// </summary>
        internal static string Description_EAssetType_OBJECT {
            get {
                return ResourceManager.GetString("Description_EAssetType_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource that can spawn on the map and be harvested..
        /// </summary>
        internal static string Description_EAssetType_RESOURCE {
            get {
                return ResourceManager.GetString("Description_EAssetType_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item or vehicle skin..
        /// </summary>
        internal static string Description_EAssetType_SKIN {
            get {
                return ResourceManager.GetString("Description_EAssetType_SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asset spawn for a map..
        /// </summary>
        internal static string Description_EAssetType_SPAWN {
            get {
                return ResourceManager.GetString("Description_EAssetType_SPAWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any vehicle..
        /// </summary>
        internal static string Description_EAssetType_VEHICLE {
            get {
                return ResourceManager.GetString("Description_EAssetType_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines properties for the behavior of the Unturned Data File Language Server..
        /// </summary>
        internal static string Description_ProjectFile {
            get {
                return ResourceManager.GetString("Description_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected function name at beginning of expression..
        /// </summary>
        internal static string FormatException_Expression_ExpectedFunctionName {
            get {
                return ResourceManager.GetString("FormatException_Expression_ExpectedFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of expression or open parenthesis after function name..
        /// </summary>
        internal static string FormatException_Expression_ExpectedFunctionStart {
            get {
                return ResourceManager.GetString("FormatException_Expression_ExpectedFunctionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of expression or next argument after parameter closing..
        /// </summary>
        internal static string FormatException_Expression_ExpectedNextArgument {
            get {
                return ResourceManager.GetString("FormatException_Expression_ExpectedNextArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected closing parenthesis at end of value..
        /// </summary>
        internal static string FormatException_Expression_ExpectedParenthesizedValueEnd {
            get {
                return ResourceManager.GetString("FormatException_Expression_ExpectedParenthesizedValueEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter list not closed, expected &apos;)&apos;..
        /// </summary>
        internal static string FormatException_Expression_MissingEndingParenthesis {
            get {
                return ResourceManager.GetString("FormatException_Expression_MissingEndingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested expressions can not be wrapped in parenthesis, such as in &quot;=(SQRT(1))&quot;..
        /// </summary>
        internal static string FormatException_Expression_NestedExpressionCanNotBeWrapped {
            get {
                return ResourceManager.GetString("FormatException_Expression_NestedExpressionCanNotBeWrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse IPv4Filter, expected a value in the format: &quot;0.0.0.0[/0][:0[-0]]&quot;..
        /// </summary>
        internal static string FormatException_IPv4Format_FailedToParse {
            get {
                return ResourceManager.GetString("FormatException_IPv4Format_FailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid count type: &apos;{0}&apos;. Expected an integer type..
        /// </summary>
        internal static string InvalidOperationException_InvalidCountType {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidCountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vector type: &apos;{0}&apos;. Annotate the type with a {1} to define a vector provider..
        /// </summary>
        internal static string InvalidOperationException_InvalidVectorType {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidVectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; didn&apos;t define a value string..
        /// </summary>
        internal static string JsonException_EnumMissingValue {
            get {
                return ResourceManager.GetString("JsonException_EnumMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse enum of type {0} from value &quot;{1}&quot; in file &quot;{2}&quot;..
        /// </summary>
        internal static string JsonException_FailedToParseEnum {
            get {
                return ResourceManager.GetString("JsonException_FailedToParseEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse value of type &quot;{0}&quot; in file &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_FailedToParseValue {
            get {
                return ResourceManager.GetString("JsonException_FailedToParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read value of type {0} from JSON at {1}..
        /// </summary>
        internal static string JsonException_FailedToReadValue {
            get {
                return ResourceManager.GetString("JsonException_FailedToReadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag enum value &quot;{0}&quot; did not define a numeric value, which is required for flag enum values..
        /// </summary>
        internal static string JsonException_FlagEnumMissingNumericValue {
            get {
                return ResourceManager.GetString("JsonException_FlagEnumMissingNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &quot;{0}&quot; while reading file &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_InvalidJsonToken {
            get {
                return ResourceManager.GetString("JsonException_InvalidJsonToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; template group at index {1} couldn&apos;t be parsed..
        /// </summary>
        internal static string JsonException_InvalidTemplateGroup {
            get {
                return ResourceManager.GetString("JsonException_InvalidTemplateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Type&quot; property was set to &quot;{0}&quot; in the file type definition for &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_InvalidTypeInDatFileType {
            get {
                return ResourceManager.GetString("JsonException_InvalidTypeInDatFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a property named &quot;{0}&quot; in any parent types to override in file &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_OverriddenPropertyNotFound {
            get {
                return ResourceManager.GetString("JsonException_OverriddenPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate parent type &quot;{0}&quot; for type &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_ParentTypeNotFound {
            get {
                return ResourceManager.GetString("JsonException_ParentTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; doesn&apos;t define a key, which is required..
        /// </summary>
        internal static string JsonException_PropertyKeyMissing {
            get {
                return ResourceManager.GetString("JsonException_PropertyKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; doesn&apos;t define a type, which is required unless the property is updating/hiding a base property..
        /// </summary>
        internal static string JsonException_PropertyTypeMissing {
            get {
                return ResourceManager.GetString("JsonException_PropertyTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type &quot;{0}&quot; for property &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_PropertyTypeNotFound {
            get {
                return ResourceManager.GetString("JsonException_PropertyTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required property &quot;{0}&quot; for type &quot;{1}&quot; missing in file &quot;{2}&quot;..
        /// </summary>
        internal static string JsonException_RequiredTypePropertyMissing {
            get {
                return ResourceManager.GetString("JsonException_RequiredTypePropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; does not define a &quot;Type&quot; property with a type name..
        /// </summary>
        internal static string JsonException_TypeMissingTypeName {
            get {
                return ResourceManager.GetString("JsonException_TypeMissingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; can not be defined with &quot;{1}&quot;..
        /// </summary>
        internal static string JsonException_UnexpectedProperty {
            get {
                return ResourceManager.GetString("JsonException_UnexpectedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download internet resource at &quot;{0}&quot;..
        /// </summary>
        internal static string Log_FailedToDownloadInternetResource {
            get {
                return ResourceManager.GetString("Log_FailedToDownloadInternetResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate embedded resource &quot;{0}&quot;, which was expected to exist..
        /// </summary>
        internal static string Log_FailedToFindEmbeddedResource {
            get {
                return ResourceManager.GetString("Log_FailedToFindEmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find string-parseable type &quot;{0}&quot; for custom type &quot;{1}&quot;..
        /// </summary>
        internal static string Log_FailedToFindStringParseableType {
            get {
                return ResourceManager.GetString("Log_FailedToFindStringParseableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read resource at &quot;{0}&quot;..
        /// </summary>
        internal static string Log_FailedToParseResource {
            get {
                return ResourceManager.GetString("Log_FailedToParseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read specification for type &quot;{0}&quot;. This type and all child types will be skipped..
        /// </summary>
        internal static string Log_FailedToReadAssetFile {
            get {
                return ResourceManager.GetString("Log_FailedToReadAssetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read latest commit hash from GitHub API. They may have changed their API or the current network is being blocked..
        /// </summary>
        internal static string Log_FailedToReadCommitHashFromRepo {
            get {
                return ResourceManager.GetString("Log_FailedToReadCommitHashFromRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet resource at &quot;{0}&quot; is corrupted..
        /// </summary>
        internal static string Log_InternetResourceCorrupted {
            get {
                return ResourceManager.GetString("Log_InternetResourceCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read file &quot;{0}&quot; from any of the available sources..
        /// </summary>
        internal static string Log_UnableToReadFile {
            get {
                return ResourceManager.GetString("Log_UnableToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset type corresponding to &apos;{0}&apos;..
        /// </summary>
        internal static string Type_AssetTypeAlias_Description {
            get {
                return ResourceManager.GetString("Type_AssetTypeAlias_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Button Label.
        /// </summary>
        internal static string Type_Name_ActionKey {
            get {
                return ResourceManager.GetString("Type_Name_ActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference.
        /// </summary>
        internal static string Type_Name_AssetReference {
            get {
                return ResourceManager.GetString("Type_Name_AssetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference to {0}.
        /// </summary>
        internal static string Type_Name_AssetReference_Type {
            get {
                return ResourceManager.GetString("Type_Name_AssetReference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference (String).
        /// </summary>
        internal static string Type_Name_AssetReferenceString {
            get {
                return ResourceManager.GetString("Type_Name_AssetReferenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference (String) to {0}.
        /// </summary>
        internal static string Type_Name_AssetReferenceString_Type {
            get {
                return ResourceManager.GetString("Type_Name_AssetReferenceString_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        internal static string Type_Name_AssetTypeAlias {
            get {
                return ResourceManager.GetString("Type_Name_AssetTypeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Reference.
        /// </summary>
        internal static string Type_Name_AudioReference {
            get {
                return ResourceManager.GetString("Type_Name_AudioReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference (Backwards-Compatible).
        /// </summary>
        internal static string Type_Name_BackwardsCompatibleAssetReferenceBcAssetReference {
            get {
                return ResourceManager.GetString("Type_Name_BackwardsCompatibleAssetReferenceBcAssetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference to {0} (Backwards-Compatible).
        /// </summary>
        internal static string Type_Name_BackwardsCompatibleAssetReferenceBcAssetReference_Type {
            get {
                return ResourceManager.GetString("Type_Name_BackwardsCompatibleAssetReferenceBcAssetReference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference (String, Backwards-Compatible).
        /// </summary>
        internal static string Type_Name_BackwardsCompatibleAssetReferenceBcAssetReferenceString {
            get {
                return ResourceManager.GetString("Type_Name_BackwardsCompatibleAssetReferenceBcAssetReferenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference (String) to {0} (Backwards-Compatible).
        /// </summary>
        internal static string Type_Name_BackwardsCompatibleAssetReferenceBcAssetReferenceString_Type {
            get {
                return ResourceManager.GetString("Type_Name_BackwardsCompatibleAssetReferenceBcAssetReferenceString_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference (GUID or ID).
        /// </summary>
        internal static string Type_Name_BackwardsCompatibleAssetReferenceGuidOrLegacyId {
            get {
                return ResourceManager.GetString("Type_Name_BackwardsCompatibleAssetReferenceGuidOrLegacyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Reference to {0} (GUID or ID).
        /// </summary>
        internal static string Type_Name_BackwardsCompatibleAssetReferenceGuidOrLegacyId_Type {
            get {
                return ResourceManager.GetString("Type_Name_BackwardsCompatibleAssetReferenceGuidOrLegacyId_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beard Index.
        /// </summary>
        internal static string Type_Name_BeardIndex {
            get {
                return ResourceManager.GetString("Type_Name_BeardIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill (or Legacy Blueprint Skill).
        /// </summary>
        internal static string Type_Name_BlueprintSkill {
            get {
                return ResourceManager.GetString("Type_Name_BlueprintSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string Type_Name_Boolean {
            get {
                return ResourceManager.GetString("Type_Name_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean or Flag.
        /// </summary>
        internal static string Type_Name_BooleanOrFlag {
            get {
                return ResourceManager.GetString("Type_Name_BooleanOrFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Type_Name_Character {
            get {
                return ResourceManager.GetString("Type_Name_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color (0-1).
        /// </summary>
        internal static string Type_Name_Color {
            get {
                return ResourceManager.GetString("Type_Name_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color (0-255, Legacy: 0-1).
        /// </summary>
        internal static string Type_Name_Color_ModernIs32Bit {
            get {
                return ResourceManager.GetString("Type_Name_Color_ModernIs32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color (0-255).
        /// </summary>
        internal static string Type_Name_Color32 {
            get {
                return ResourceManager.GetString("Type_Name_Color32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-Separated List of {0}.
        /// </summary>
        internal static string Type_Name_CommaDelimitedString_Generic {
            get {
                return ResourceManager.GetString("Type_Name_CommaDelimitedString_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Reference.
        /// </summary>
        internal static string Type_Name_ContentReference {
            get {
                return ResourceManager.GetString("Type_Name_ContentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp (UTC).
        /// </summary>
        internal static string Type_Name_DateTime {
            get {
                return ResourceManager.GetString("Type_Name_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp + Timezone.
        /// </summary>
        internal static string Type_Name_DateTimeOffset {
            get {
                return ResourceManager.GetString("Type_Name_DateTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary of {0} to {1}.
        /// </summary>
        internal static string Type_Name_Dictionary_Generic {
            get {
                return ResourceManager.GetString("Type_Name_Dictionary_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary of {0}.
        /// </summary>
        internal static string Type_Name_Dictionary_Generic_String {
            get {
                return ResourceManager.GetString("Type_Name_Dictionary_Generic_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Category.
        /// </summary>
        internal static string Type_Name_EAssetType {
            get {
                return ResourceManager.GetString("Type_Name_EAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Index.
        /// </summary>
        internal static string Type_Name_FaceIndex {
            get {
                return ResourceManager.GetString("Type_Name_FaceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string Type_Name_Flag {
            get {
                return ResourceManager.GetString("Type_Name_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Flag ID.
        /// </summary>
        internal static string Type_Name_FlagId {
            get {
                return ResourceManager.GetString("Type_Name_FlagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string Type_Name_Float128 {
            get {
                return ResourceManager.GetString("Type_Name_Float128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-Precision Decimal.
        /// </summary>
        internal static string Type_Name_Float32 {
            get {
                return ResourceManager.GetString("Type_Name_Float32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Precision Decimal.
        /// </summary>
        internal static string Type_Name_Float64 {
            get {
                return ResourceManager.GetString("Type_Name_Float64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        internal static string Type_Name_Guid {
            get {
                return ResourceManager.GetString("Type_Name_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID or Unsigned 16-Bit Integer.
        /// </summary>
        internal static string Type_Name_GuidOrId {
            get {
                return ResourceManager.GetString("Type_Name_GuidOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairstyle Index.
        /// </summary>
        internal static string Type_Name_HairIndex {
            get {
                return ResourceManager.GetString("Type_Name_HairIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 16-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int16 {
            get {
                return ResourceManager.GetString("Type_Name_Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 32-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int32 {
            get {
                return ResourceManager.GetString("Type_Name_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 64-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int64 {
            get {
                return ResourceManager.GetString("Type_Name_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 8-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int8 {
            get {
                return ResourceManager.GetString("Type_Name_Int8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Filter.
        /// </summary>
        internal static string Type_Name_IPv4Filter {
            get {
                return ResourceManager.GetString("Type_Name_IPv4Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Asset Reference.
        /// </summary>
        internal static string Type_Name_LegacyAssetReference {
            get {
                return ResourceManager.GetString("Type_Name_LegacyAssetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Asset Reference to {0}.
        /// </summary>
        internal static string Type_Name_LegacyAssetReference_Type {
            get {
                return ResourceManager.GetString("Type_Name_LegacyAssetReference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of {0}.
        /// </summary>
        internal static string Type_Name_List_Generic {
            get {
                return ResourceManager.GetString("Type_Name_List_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizable Text.
        /// </summary>
        internal static string Type_Name_LocalizableString {
            get {
                return ResourceManager.GetString("Type_Name_LocalizableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizable Rich Text.
        /// </summary>
        internal static string Type_Name_LocalizableString_Rich {
            get {
                return ResourceManager.GetString("Type_Name_LocalizableString_Rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Key.
        /// </summary>
        internal static string Type_Name_LocalizationKey {
            get {
                return ResourceManager.GetString("Type_Name_LocalizationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Key for Rich Text.
        /// </summary>
        internal static string Type_Name_LocalizationKey_Rich {
            get {
                return ResourceManager.GetString("Type_Name_LocalizationKey_Rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterbundle or Content Reference.
        /// </summary>
        internal static string Type_Name_MasterBundleOrContentReference {
            get {
                return ResourceManager.GetString("Type_Name_MasterBundleOrContentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterbundle Reference.
        /// </summary>
        internal static string Type_Name_MasterBundleReference {
            get {
                return ResourceManager.GetString("Type_Name_MasterBundleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterbundle Reference (Legacy).
        /// </summary>
        internal static string Type_Name_MasterBundleReferenceString {
            get {
                return ResourceManager.GetString("Type_Name_MasterBundleReferenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navmesh ID.
        /// </summary>
        internal static string Type_Name_NavId {
            get {
                return ResourceManager.GetString("Type_Name_NavId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Achievement ID.
        /// </summary>
        internal static string Type_Name_NPCAchievementId {
            get {
                return ResourceManager.GetString("Type_Name_NPCAchievementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Type.
        /// </summary>
        internal static string Type_Name_NullType {
            get {
                return ResourceManager.GetString("Type_Name_NullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderfile.
        /// </summary>
        internal static string Type_Name_Orderfile {
            get {
                return ResourceManager.GetString("Type_Name_Orderfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderfile Property Reference.
        /// </summary>
        internal static string Type_Name_OrderfilePropertyReference {
            get {
                return ResourceManager.GetString("Type_Name_OrderfilePropertyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Overlap Volume ID.
        /// </summary>
        internal static string Type_Name_OverlapVolumeId {
            get {
                return ResourceManager.GetString("Type_Name_OverlapVolumeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File.
        /// </summary>
        internal static string Type_Name_ProjectFile {
            get {
                return ResourceManager.GetString("Type_Name_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly-Qualified C# Type Name.
        /// </summary>
        internal static string Type_Name_QualifiedType {
            get {
                return ResourceManager.GetString("Type_Name_QualifiedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression (RegEx).
        /// </summary>
        internal static string Type_Name_RegEx {
            get {
                return ResourceManager.GetString("Type_Name_RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string Type_Name_Skill {
            get {
                return ResourceManager.GetString("Type_Name_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level.
        /// </summary>
        internal static string Type_Name_SkillLevel {
            get {
                return ResourceManager.GetString("Type_Name_SkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawnpoint ID.
        /// </summary>
        internal static string Type_Name_SpawnpointId {
            get {
                return ResourceManager.GetString("Type_Name_SpawnpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam64 ID ({0}).
        /// </summary>
        internal static string Type_Name_Steam64ID {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous Game Server.
        /// </summary>
        internal static string Type_Name_Steam64ID_AnonGameServer {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_AnonGameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous User.
        /// </summary>
        internal static string Type_Name_Steam64ID_AnonUser {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_AnonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Type_Name_Steam64ID_Any {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Chat.
        /// </summary>
        internal static string Type_Name_Steam64ID_Chat {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Type_Name_Steam64ID_Clan {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console User.
        /// </summary>
        internal static string Type_Name_Steam64ID_ConsoleUser {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_ConsoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Server.
        /// </summary>
        internal static string Type_Name_Steam64ID_ContentServer {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_ContentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Server.
        /// </summary>
        internal static string Type_Name_Steam64ID_GameServer {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_GameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string Type_Name_Steam64ID_Individual {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Type_Name_Steam64ID_Join {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiseat Account.
        /// </summary>
        internal static string Type_Name_Steam64ID_Multiseat {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Multiseat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Entity.
        /// </summary>
        internal static string Type_Name_Steam64ID_Pending {
            get {
                return ResourceManager.GetString("Type_Name_Steam64ID_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Item Identifier.
        /// </summary>
        internal static string Type_Name_SteamItemDef {
            get {
                return ResourceManager.GetString("Type_Name_SteamItemDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Type_Name_String {
            get {
                return ResourceManager.GetString("Type_Name_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Type_Name_TimeSpan {
            get {
                return ResourceManager.GetString("Type_Name_TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Translation Token Reference.
        /// </summary>
        internal static string Type_Name_TranslationReference {
            get {
                return ResourceManager.GetString("Type_Name_TranslationReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Reference.
        /// </summary>
        internal static string Type_Name_TypeReference {
            get {
                return ResourceManager.GetString("Type_Name_TypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Reference of {0}.
        /// </summary>
        internal static string Type_Name_TypeReference_Type {
            get {
                return ResourceManager.GetString("Type_Name_TypeReference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        internal static string Type_Name_TypeReference_TypeOrEnum {
            get {
                return ResourceManager.GetString("Type_Name_TypeReference_TypeOrEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 16-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt16 {
            get {
                return ResourceManager.GetString("Type_Name_UInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 32-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt32 {
            get {
                return ResourceManager.GetString("Type_Name_UInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 64-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt64 {
            get {
                return ResourceManager.GetString("Type_Name_UInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 8-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt8 {
            get {
                return ResourceManager.GetString("Type_Name_UInt8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Type.
        /// </summary>
        internal static string Type_Name_ValueType {
            get {
                return ResourceManager.GetString("Type_Name_ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Vector.
        /// </summary>
        internal static string Type_Name_Vector2_Unspecified {
            get {
                return ResourceManager.GetString("Type_Name_Vector2_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Position.
        /// </summary>
        internal static string Type_Name_Vector3_Position {
            get {
                return ResourceManager.GetString("Type_Name_Vector3_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Euler Rotation.
        /// </summary>
        internal static string Type_Name_Vector3_Rotation {
            get {
                return ResourceManager.GetString("Type_Name_Vector3_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Scale.
        /// </summary>
        internal static string Type_Name_Vector3_Scale {
            get {
                return ResourceManager.GetString("Type_Name_Vector3_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Vector.
        /// </summary>
        internal static string Type_Name_Vector3_Unspecified {
            get {
                return ResourceManager.GetString("Type_Name_Vector3_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaternion.
        /// </summary>
        internal static string Type_Name_Vector4_Quaternion {
            get {
                return ResourceManager.GetString("Type_Name_Vector4_Quaternion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4D Vector.
        /// </summary>
        internal static string Type_Name_Vector4_Unspecified {
            get {
                return ResourceManager.GetString("Type_Name_Vector4_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        internal static string Type_Name_Version {
            get {
                return ResourceManager.GetString("Type_Name_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombie Cooldown ID.
        /// </summary>
        internal static string Type_Name_ZombieCooldownId {
            get {
                return ResourceManager.GetString("Type_Name_ZombieCooldownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombie Table ID.
        /// </summary>
        internal static string Type_Name_ZombieTableId {
            get {
                return ResourceManager.GetString("Type_Name_ZombieTableId", resourceCulture);
            }
        }
    }
}
