//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDataFileLspServer.Data.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDataFileLspServer.Data.Diagnostics.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary and list properties can not also supply a value..
        /// </summary>
        public static string UNT1001 {
            get {
                return ResourceManager.GetString("UNT1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected double quotation mark at end of quoted string..
        /// </summary>
        public static string UNT1002 {
            get {
                return ResourceManager.GetString("UNT1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is a flag, meaning just the presence of the property indicates a &apos;true&apos; value. The dictionary will be ignored..
        /// </summary>
        public static string UNT1003_Dictionary {
            get {
                return ResourceManager.GetString("UNT1003_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is a flag, meaning just the presence of the property indicates a &apos;true&apos; value. The list will be ignored..
        /// </summary>
        public static string UNT1003_List {
            get {
                return ResourceManager.GetString("UNT1003_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is a flag, meaning just the presence of the property indicates a &apos;true&apos; value. The &apos;{1}&apos; value will be ignored..
        /// </summary>
        public static string UNT1003_Value {
            get {
                return ResourceManager.GetString("UNT1003_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence &apos;\{0}&apos; not recognized. Expected &apos;\n&apos;, &apos;\t&apos;, &apos;\&quot;&apos;, or &apos;\\&apos;..
        /// </summary>
        public static string UNT1004 {
            get {
                return ResourceManager.GetString("UNT1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-quotation marks can not be escaped in non-quoted strings. Use quoted strings if the first character needs to be a double-quotation mark. For example: &quot;\&quot;Value\&quot;&quot;, which parses to [&quot;Value&quot;]..
        /// </summary>
        public static string UNT1004_LeadingEscapedSlash {
            get {
                return ResourceManager.GetString("UNT1004_LeadingEscapedSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing unescaped backslash. Use two backslashes to escape a backslash: &apos;\\&apos;..
        /// </summary>
        public static string UNT1004_Trailing {
            get {
                return ResourceManager.GetString("UNT1004_Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property does not support rich text..
        /// </summary>
        public static string UNT1006 {
            get {
                return ResourceManager.GetString("UNT1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; requires property &apos;{1}&apos; to be present..
        /// </summary>
        public static string UNT1007 {
            get {
                return ResourceManager.GetString("UNT1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; requires a value for &apos;{1}&apos;..
        /// </summary>
        public static string UNT1007_Modern {
            get {
                return ResourceManager.GetString("UNT1007_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a face with index {0}, valid indexes include 0 through {1}..
        /// </summary>
        public static string UNT1008_Beard {
            get {
                return ResourceManager.GetString("UNT1008_Beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a beard with index {0}, valid indexes include 0 through {1}..
        /// </summary>
        public static string UNT1008_Face {
            get {
                return ResourceManager.GetString("UNT1008_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a hair with index {0}, valid indexes include 0 through {1}..
        /// </summary>
        public static string UNT1008_Hair {
            get {
                return ResourceManager.GetString("UNT1008_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset bundle version, expected a value between {0} and {1}..
        /// </summary>
        public static string UNT1009 {
            get {
                return ResourceManager.GetString("UNT1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint supply IDs that are the same as their containing asset can be replaced with &apos;This&apos;..
        /// </summary>
        public static string UNT101 {
            get {
                return ResourceManager.GetString("UNT101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;this&quot; keyword can be used to reference the current asset instead of using an ID or GUID..
        /// </summary>
        public static string UNT101_CodeFix_Annotation_Desc {
            get {
                return ResourceManager.GetString("UNT101_CodeFix_Annotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;this&quot; Keyword.
        /// </summary>
        public static string UNT101_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT101_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths should only use forward slashes to maintain compatibility with Unity and Unix-based operating systems..
        /// </summary>
        public static string UNT1010 {
            get {
                return ResourceManager.GetString("UNT1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path should match pattern &quot;{0}&quot;..
        /// </summary>
        public static string UNT1011 {
            get {
                return ResourceManager.GetString("UNT1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This legacy color is expected to have components between 0 and 1. Using values outside this range may cause unexpected results or visual glitches..
        /// </summary>
        public static string UNT1012 {
            get {
                return ResourceManager.GetString("UNT1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement ID &quot;{0}&quot; either doesn&apos;t exist or isn&apos;t a valid NPC achievement..
        /// </summary>
        public static string UNT1013 {
            get {
                return ResourceManager.GetString("UNT1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        public static string UNT1014 {
            get {
                return ResourceManager.GetString("UNT1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one value in &quot;{0}&quot; of enum &quot;{1}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        public static string UNT1014_Flags {
            get {
                return ResourceManager.GetString("UNT1014_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; of enum &quot;{1}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        public static string UNT1014_Specific {
            get {
                return ResourceManager.GetString("UNT1014_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a type deriving from &apos;{0}&apos;..
        /// </summary>
        public static string UNT1015 {
            get {
                return ResourceManager.GetString("UNT1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} is not a valid level for the {1} skill..
        /// </summary>
        public static string UNT1016 {
            get {
                return ResourceManager.GetString("UNT1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill level {0} should not exceed {1}..
        /// </summary>
        public static string UNT1016_Generic {
            get {
                return ResourceManager.GetString("UNT1016_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected amount supplied for an item ID or GUID..
        /// </summary>
        public static string UNT1017 {
            get {
                return ResourceManager.GetString("UNT1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is deprecated..
        /// </summary>
        public static string UNT1018 {
            get {
                return ResourceManager.GetString("UNT1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Translation Reference format is no longer supported by Unturned..
        /// </summary>
        public static string UNT1018_TranslationReference {
            get {
                return ResourceManager.GetString("UNT1018_TranslationReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property shouldn&apos;t reference the asset it&apos;s defined in..
        /// </summary>
        public static string UNT1019 {
            get {
                return ResourceManager.GetString("UNT1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This format string should include argument {{{0}}}..
        /// </summary>
        public static string UNT102 {
            get {
                return ResourceManager.GetString("UNT102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document exceeds the maximum depth of the parser, which is {0} levels..
        /// </summary>
        public static string UNT1020 {
            get {
                return ResourceManager.GetString("UNT1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-line formatting is not supported for this string..
        /// </summary>
        public static string UNT1021 {
            get {
                return ResourceManager.GetString("UNT1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct new-line tag is &quot;&lt;br&gt;&quot;. No other variations are accepted..
        /// </summary>
        public static string UNT1022 {
            get {
                return ResourceManager.GetString("UNT1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type references should use assembly-qualified type names. These are formatted as the full type and the assembly name separated by a comma. For example: &apos;SDG.Unturned.Asset, Assembly-CSharp&apos;..
        /// </summary>
        public static string UNT1023 {
            get {
                return ResourceManager.GetString("UNT1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; should must contain at least {1} element(s)..
        /// </summary>
        public static string UNT1024_Less {
            get {
                return ResourceManager.GetString("UNT1024_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; should must be at least {1} character(s) long..
        /// </summary>
        public static string UNT1024_LessString {
            get {
                return ResourceManager.GetString("UNT1024_LessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; should not contain more than {1} element(s)..
        /// </summary>
        public static string UNT1024_More {
            get {
                return ResourceManager.GetString("UNT1024_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; should not be longer than {1} character(s)..
        /// </summary>
        public static string UNT1024_MoreString {
            get {
                return ResourceManager.GetString("UNT1024_MoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property &quot;{0}&quot;. If you believe this is an error please open an issue on the GitHub page for this extension..
        /// </summary>
        public static string UNT1025 {
            get {
                return ResourceManager.GetString("UNT1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this property from the asset file since it&apos;s not recognized by Unturned..
        /// </summary>
        public static string UNT1025_CodeFix_Annotation_Desc {
            get {
                return ResourceManager.GetString("UNT1025_CodeFix_Annotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &quot;{0}&quot; Property.
        /// </summary>
        public static string UNT1025_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT1025_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; only supports the red, green, and blue components, not alpha..
        /// </summary>
        public static string UNT1026 {
            get {
                return ResourceManager.GetString("UNT1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; shouldn&apos;t contain duplicate values. Element {1} is the same as element {2}..
        /// </summary>
        public static string UNT1027 {
            get {
                return ResourceManager.GetString("UNT1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; (&quot;{1}&quot;) should not be &quot;{2}&quot; or higher..
        /// </summary>
        public static string UNT1028_Maximum_Exclusive {
            get {
                return ResourceManager.GetString("UNT1028_Maximum_Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; should not be &quot;{1}&quot; or higher..
        /// </summary>
        public static string UNT1028_Maximum_Exclusive_Anonymous {
            get {
                return ResourceManager.GetString("UNT1028_Maximum_Exclusive_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; (&quot;{1}&quot;) should not be higher than &quot;{2}&quot;..
        /// </summary>
        public static string UNT1028_Maximum_Inclusive {
            get {
                return ResourceManager.GetString("UNT1028_Maximum_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; should not be higher than &quot;{1}&quot;..
        /// </summary>
        public static string UNT1028_Maximum_Inclusive_Anonymous {
            get {
                return ResourceManager.GetString("UNT1028_Maximum_Inclusive_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; (&quot;{1}&quot;) should not be &quot;{2}&quot; or lower..
        /// </summary>
        public static string UNT1028_Minimum_Exclusive {
            get {
                return ResourceManager.GetString("UNT1028_Minimum_Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; should not be &quot;{1}&quot; or less..
        /// </summary>
        public static string UNT1028_Minimum_Exclusive_Anonymous {
            get {
                return ResourceManager.GetString("UNT1028_Minimum_Exclusive_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; (&quot;{1}&quot;) should not be less than &quot;{2}&quot;..
        /// </summary>
        public static string UNT1028_Minimum_Inclusive {
            get {
                return ResourceManager.GetString("UNT1028_Minimum_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; should not be less than &quot;{1}&quot;..
        /// </summary>
        public static string UNT1028_Minimum_Inclusive_Anonymous {
            get {
                return ResourceManager.GetString("UNT1028_Minimum_Inclusive_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; doesn&apos;t accept Steam64 IDs with the account type &quot;{1}&quot;. Make sure this ID is the correct type..
        /// </summary>
        public static string UNT1029 {
            get {
                return ResourceManager.GetString("UNT1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for property &apos;{0}&apos; doesn&apos;t appear to be a correctly formed Steam64 ID..
        /// </summary>
        public static string UNT1029_Invalid {
            get {
                return ResourceManager.GetString("UNT1029_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is unknown and may not be assignable to &apos;{1}&apos;..
        /// </summary>
        public static string UNT103 {
            get {
                return ResourceManager.GetString("UNT103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; expected a localization file to be present for this asset..
        /// </summary>
        public static string UNT1030_Property {
            get {
                return ResourceManager.GetString("UNT1030_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization property &apos;{0}&apos; is required but a localization file doesn&apos;t exist for this asset..
        /// </summary>
        public static string UNT1030_RequiredLocal {
            get {
                return ResourceManager.GetString("UNT1030_RequiredLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version has {0} digits, where it should have exactly {1} digits..
        /// </summary>
        public static string UNT1031_Digits {
            get {
                return ResourceManager.GetString("UNT1031_Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build version {0} is too small. Value should not be less than {1}..
        /// </summary>
        public static string UNT1031_Less_Build {
            get {
                return ResourceManager.GetString("UNT1031_Less_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version {0} is too small. Value should not be less than {1}..
        /// </summary>
        public static string UNT1031_Less_Major {
            get {
                return ResourceManager.GetString("UNT1031_Less_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor version {0} is too small. Value should not be less than {1}..
        /// </summary>
        public static string UNT1031_Less_Minor {
            get {
                return ResourceManager.GetString("UNT1031_Less_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision version {0} is too small. Value should not be less than {1}..
        /// </summary>
        public static string UNT1031_Less_Revision {
            get {
                return ResourceManager.GetString("UNT1031_Less_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build version {0} is too large. Value should not exceed {1}..
        /// </summary>
        public static string UNT1031_More_Build {
            get {
                return ResourceManager.GetString("UNT1031_More_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version {0} is too large. Value should not exceed {1}..
        /// </summary>
        public static string UNT1031_More_Major {
            get {
                return ResourceManager.GetString("UNT1031_More_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor version {0} is too large. Value should not exceed {1}..
        /// </summary>
        public static string UNT1031_More_Minor {
            get {
                return ResourceManager.GetString("UNT1031_More_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision version {0} is too large. Value should not exceed {1}..
        /// </summary>
        public static string UNT1031_More_Revision {
            get {
                return ResourceManager.GetString("UNT1031_More_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dictionary contains multiple &apos;{0}&apos; properties. This property overrides all others with the same name..
        /// </summary>
        public static string UNT1032 {
            get {
                return ResourceManager.GetString("UNT1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MasterBundleReference (&quot;MasterBundle&quot;, &quot;AssetPath&quot;) format is preferred here over the legacy ContentReference (&quot;Name&quot;, &quot;Path&quot;) format..
        /// </summary>
        public static string UNT104 {
            get {
                return ResourceManager.GetString("UNT104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary trailing comma after quoted string..
        /// </summary>
        public static string UNT105 {
            get {
                return ResourceManager.GetString("UNT105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;&lt;br&gt;&quot; instead of an explicit new-line..
        /// </summary>
        public static string UNT106 {
            get {
                return ResourceManager.GetString("UNT106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a new GUID in the same format as the current one..
        /// </summary>
        public static string UNT107_CodeFix_Annotation_Desc {
            get {
                return ResourceManager.GetString("UNT107_CodeFix_Annotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Random GUID.
        /// </summary>
        public static string UNT107_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT107_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce to string format..
        /// </summary>
        public static string UNT108 {
            get {
                return ResourceManager.GetString("UNT108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string format of bundle references is more concise and easy to read..
        /// </summary>
        public static string UNT108_CodeFix_Annotation_Description {
            get {
                return ResourceManager.GetString("UNT108_CodeFix_Annotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce to string format: &quot;{0}&quot;..
        /// </summary>
        public static string UNT108_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT108_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the skill referenced by this property. Expected a speciality index at property &quot;{0}&quot; and a skill index at property &quot;{1}&quot;..
        /// </summary>
        public static string UNT109_Indices {
            get {
                return ResourceManager.GetString("UNT109_Indices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the skill referenced by this property. Expected a skill name at property &quot;{0}&quot;..
        /// </summary>
        public static string UNT109_Skill {
            get {
                return ResourceManager.GetString("UNT109_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;}&apos; at end of dictionary..
        /// </summary>
        public static string UNT2001 {
            get {
                return ResourceManager.GetString("UNT2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;]&apos; at end of list..
        /// </summary>
        public static string UNT2002 {
            get {
                return ResourceManager.GetString("UNT2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is a flag, meaning just the presence of the property indicates a &apos;true&apos; value. The &apos;{1}&apos; value will be ignored..
        /// </summary>
        public static string UNT2003 {
            get {
                return ResourceManager.GetString("UNT2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;..
        /// </summary>
        public static string UNT2004 {
            get {
                return ResourceManager.GetString("UNT2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;, which expects a GUID as a string only. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_AssetReferenceStringOnly {
            get {
                return ResourceManager.GetString("UNT2004_AssetReferenceStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;, which expects a GUID, ID, or TYPE:ID as a string only. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_BackwardsCompatibleAssetReferenceStringOnly {
            get {
                return ResourceManager.GetString("UNT2004_BackwardsCompatibleAssetReferenceStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;. Single-character boolean values must be lowercase, try using &quot;{2}&quot; instead..
        /// </summary>
        public static string UNT2004_BooleanSingleCharCapitalized {
            get {
                return ResourceManager.GetString("UNT2004_BooleanSingleCharCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;, which expects bundle references in the format &quot;name:path&quot;. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_BundleReferenceStringOnly {
            get {
                return ResourceManager.GetString("UNT2004_BundleReferenceStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the type of property &apos;{0}&apos;. This is likely a bug in the asset specification..
        /// </summary>
        public static string UNT2004_CanNotDetermineType {
            get {
                return ResourceManager.GetString("UNT2004_CanNotDetermineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;. Property &apos;{1}&apos; expects a list..
        /// </summary>
        public static string UNT2004_DictionaryInsteadOfList {
            get {
                return ResourceManager.GetString("UNT2004_DictionaryInsteadOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_DictionaryInsteadOfValue {
            get {
                return ResourceManager.GetString("UNT2004_DictionaryInsteadOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;, which expects an ID as a string only. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_LegacyAssetReferenceStringOnly {
            get {
                return ResourceManager.GetString("UNT2004_LegacyAssetReferenceStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; can only be expressed using the legacy object format using underscores..
        /// </summary>
        public static string UNT2004_LegacyFormatExpected {
            get {
                return ResourceManager.GetString("UNT2004_LegacyFormatExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List can not be converted to a value of type &apos;{0}&apos;. Property &apos;{1}&apos; expects a dictionary..
        /// </summary>
        public static string UNT2004_ListInsteadOfDictionary {
            get {
                return ResourceManager.GetString("UNT2004_ListInsteadOfDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List can not be converted to a value of type &apos;{0}&apos;. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_ListInsteadOfValue {
            get {
                return ResourceManager.GetString("UNT2004_ListInsteadOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; can not be parsed because it relies on values in a file that doesn&apos;t exist (like a localization file)..
        /// </summary>
        public static string UNT2004_MissingFile {
            get {
                return ResourceManager.GetString("UNT2004_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; expects a dictionary..
        /// </summary>
        public static string UNT2004_NoDictionary {
            get {
                return ResourceManager.GetString("UNT2004_NoDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; expects a list..
        /// </summary>
        public static string UNT2004_NoList {
            get {
                return ResourceManager.GetString("UNT2004_NoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; expects a value..
        /// </summary>
        public static string UNT2004_NoValue {
            get {
                return ResourceManager.GetString("UNT2004_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a regular expression..
        /// </summary>
        public static string UNT2004_Regex {
            get {
                return ResourceManager.GetString("UNT2004_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;. Property &apos;{2}&apos; is parsed in a more strict format and should be exactly {3} characters. For example: &quot;{4}&quot;..
        /// </summary>
        public static string UNT2004_StrictColor {
            get {
                return ResourceManager.GetString("UNT2004_StrictColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary can not be converted to a value of type &apos;{0}&apos;, which expects a type name as a string only. Property &apos;{1}&apos; expects a value..
        /// </summary>
        public static string UNT2004_TypeReferenceStringOnly {
            get {
                return ResourceManager.GetString("UNT2004_TypeReferenceStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;. Property &apos;{2}&apos; expects a dictionary..
        /// </summary>
        public static string UNT2004_ValueInsteadOfDictionary {
            get {
                return ResourceManager.GetString("UNT2004_ValueInsteadOfDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;. Property &apos;{2}&apos; expects a list..
        /// </summary>
        public static string UNT2004_ValueInsteadOfList {
            get {
                return ResourceManager.GetString("UNT2004_ValueInsteadOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can not be resolved..
        /// </summary>
        public static string UNT2005 {
            get {
                return ResourceManager.GetString("UNT2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type can not be determined for property &apos;{0}&apos;..
        /// </summary>
        public static string UNT2005_Property {
            get {
                return ResourceManager.GetString("UNT2005_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset bundle version, expected a value between {0} and {1}..
        /// </summary>
        public static string UNT2009 {
            get {
                return ResourceManager.GetString("UNT2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GUID is required for this asset..
        /// </summary>
        public static string UNT2010 {
            get {
                return ResourceManager.GetString("UNT2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A legacy ID is required for this asset..
        /// </summary>
        public static string UNT2011 {
            get {
                return ResourceManager.GetString("UNT2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed format string. This could be caused by having too many formatting arguments. Read about format strings here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-string-format#get-started-with-the-stringformat-method..
        /// </summary>
        public static string UNT2012 {
            get {
                return ResourceManager.GetString("UNT2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed format string: {0} This could be caused by having too many formatting arguments. Read about format strings here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-string-format#get-started-with-the-stringformat-method..
        /// </summary>
        public static string UNT2012_WithMessage {
            get {
                return ResourceManager.GetString("UNT2012_WithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} object can not be parsed using the legacy object format..
        /// </summary>
        public static string UNT2013_Legacy {
            get {
                return ResourceManager.GetString("UNT2013_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} object can not be parsed using the modern object format..
        /// </summary>
        public static string UNT2013_Modern {
            get {
                return ResourceManager.GetString("UNT2013_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required property &apos;{0}&apos; is not supplied..
        /// </summary>
        public static string UNT2014_File {
            get {
                return ResourceManager.GetString("UNT2014_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required property &apos;{0}&apos; is not supplied in &quot;{1}&quot;..
        /// </summary>
        public static string UNT2014_Object {
            get {
                return ResourceManager.GetString("UNT2014_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dictionary contains multiple &apos;{0}&apos; properties. This property has no effect..
        /// </summary>
        public static string UNT2032 {
            get {
                return ResourceManager.GetString("UNT2032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; should use the following casing: &quot;{1}&quot;..
        /// </summary>
        public static string UPROJ1001 {
            get {
                return ResourceManager.GetString("UPROJ1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; should use the following casing: &quot;{1}&quot;..
        /// </summary>
        public static string UPROJ1002 {
            get {
                return ResourceManager.GetString("UPROJ1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; doesn&apos;t exist. Double-check the spelling of the property name. Template properties should be referred to using &apos;#&apos; in place of the numbers..
        /// </summary>
        public static string UPROJ2001 {
            get {
                return ResourceManager.GetString("UPROJ2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; doesn&apos;t exist. Double-check the spelling of the type name and that it is a fully-qualified type name..
        /// </summary>
        public static string UPROJ2002 {
            get {
                return ResourceManager.GetString("UPROJ2002", resourceCulture);
            }
        }
    }
}
