<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net6.0;net481</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <LangVersion>14.0</LangVersion>

    <AssemblyName>DanielWillett.UnturnedDat.Tests</AssemblyName>
    <RootNamespace>UnturnedDat.Tests</RootNamespace>

    <EnableStaticNativeInstrumentation>False</EnableStaticNativeInstrumentation>
    <EnableDynamicNativeInstrumentation>False</EnableDynamicNativeInstrumentation>
    
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\..\test.runsettings</RunSettingsFilePath>
    
    <AppDesignerFolder>FileProperties</AppDesignerFolder>

    <StrongNameKeyPath>C:\Strong Name Keys\UnturnedAssetSpec\UnturnedAssetSpec_Tests.dll.snk</StrongNameKeyPath>
    <TestLsp>False</TestLsp>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">

    <TestLsp>True</TestLsp>
    <DefineConstants>$(DefineConstants);TEST_LSP</DefineConstants>

  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != 'net481' And exists($(StrongNameKeyPath))">
    <DefineConstants>$(DefineConstants);STRONG_NAME</DefineConstants>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(StrongNameKeyPath)</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MathMatrix\**" />
    <EmbeddedResource Remove="MathMatrix\**" />
    <None Remove="MathMatrix\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="UnturnedAssetSpec_Tests.dll.publickey" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="17.13.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />

    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.5" />

    <ProjectReference Include="../MathMatrix/MathMatrix.csproj" />
    <ProjectReference Include="../UnturnedDat/UnturnedDat.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(TestLsp)">

    <ProjectReference Include="../LanguageServer/LanguageServer.csproj" />

  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <Target Name="RemoveTestResults" AfterTargets="Clean">
    <RemoveDir Directories="$(MSBuildProjectDirectory)\..\TestResults\" Condition="Exists('$(MSBuildProjectDirectory)\..\TestResults\')" />
  </Target>

</Project>