<Project Sdk="Microsoft.NET.Sdk">

  <UsingTask AssemblyFile="../MSBuildTasks/bin/DanielWillett.UnturnedDat.MSBuildTasks.dll" TaskName="UnturnedDat.MSBuildTasks.MergeAssetSpecTask" />

  <Target Name="MergeAssetSpecFiles" BeforeTargets="Build">
    <MergeAssetSpecTask Folder="../../live-schemas" OutputFile="../../live-schemas/asset-spec.g.bin" Blacklist="Asset Spec Schema.json" />
  </Target>

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>

    <AssemblyName>DanielWillett.UnturnedDat</AssemblyName>
    <RootNamespace>UnturnedDat.Data</RootNamespace>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <StrongNameKeyPath>C:\Strong Name Keys\UnturnedAssetSpec\UnturnedAssetSpec.dll.snk</StrongNameKeyPath>
    <GenerateDependencyFile>False</GenerateDependencyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != 'netstandard2.0' And exists($(StrongNameKeyPath))">
    <DefineConstants>$(DefineConstants);STRONG_NAME</DefineConstants>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(StrongNameKeyPath)</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../live-schemas/**">
      <Link>%(RecursiveDir)/Asset Spec/%(Filename)%(Extension)</Link>
    </EmbeddedResource>
    <Compile Remove="OldTypes\**" />
    <EmbeddedResource Remove="OldTypes\**" />
    <None Remove="OldTypes\**" />
    <EmbeddedResource Remove="../Asset Spec/asset-spec.g.bin" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="UnturnedAssetSpec.csproj.Backup.tmp" />
    <None Remove="DanielWillett.UnturnedDat.dll.publickey" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Project\InstallationEnvironmentAssetBundleCache_README.md" />
  </ItemGroup>

  <ItemGroup>

    <ProjectReference Include="../MathMatrix/MathMatrix.csproj" Private="False" />

    <PackageReference Include="AssetsTools.NET" Version="3.0.5" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'" />
    <PackageReference Include="System.Text.Json" Version="4.7.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />
    <!--<PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="6.0.0" />-->
    <PackageReference Include="Microsoft.Bcl.Numerics" Version="8.0.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.14" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable" Version="1.7.1" Condition="'$(TargetFramework)' != 'net9.0'" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" Condition="'$(TargetFramework)' == 'net9.0'" />

    <PackageReference Include="System.IO.Hashing" Version="6.0.0" Condition="'$(TargetFramework)' != 'net9.0'" />
    <PackageReference Include="System.IO.Hashing" Version="9.0.0" Condition="'$(TargetFramework)' == 'net9.0'" />

    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.0" Condition="'$(TargetFramework)' != 'net9.0'" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" Condition="'$(TargetFramework)' == 'net9.0'" />

  </ItemGroup>

  <ItemGroup>
    <Compile Update="Diagnostics\DiagnosticResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DiagnosticResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Diagnostics\DiagnosticResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DiagnosticResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
