<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<RootNamespace>DanielWillett.UnturnedDat.LanguageServer</RootNamespace>
    <StrongNameKeyPath>C:\Strong Name Keys\UnturnedAssetSpec\UnturnedAssetSpec_LspServer.exe.snk</StrongNameKeyPath>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="exists($(StrongNameKeyPath))">
    <DefineConstants>$(DefineConstants);STRONG_NAME</DefineConstants>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(StrongNameKeyPath)</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UnturnedAssetSpec_LspServer.exe.publickey" />
  </ItemGroup>

	<ItemGroup>

    <ProjectReference Include="../IconHandler/IconHandler.vcxproj" ReferenceOutputAssembly="false" />

    <PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />

		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.*" />
    <!--<PackageReference Include="System.Collections.Immutable" Version="10.0.*" />-->
    <PackageReference Include="System.IO.Hashing" Version="10.0.*" />

    <PackageReference Include="DanielWillett.SpeedBytes" Version="1.1.2" />

    <ProjectReference Include="../UnturnedDat/UnturnedDat.csproj" />
	</ItemGroup>

  <ItemGroup>

    <Content Include="../IconHandler/x64/$(Configuration)/Build/**" CopyToOutputDirectory="PreserveNewest" Visible="false" />

  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
